server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/oz_news
    password: 3026606117
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka
  instance:
    prefer-ip-address: true