server:
  port: 8085

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: C:\Users\iroof\Downloads\config-service\config-service\src\main\resources\config
